# Generated by Django 5.2.1 on 2025-06-20 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('notification_type', models.CharField(choices=[('course_enrollment', 'تسجيل في دورة'), ('assignment_due', 'موعد تسليم واجب'), ('exam_reminder', 'تذكير امتحان'), ('meeting_reminder', 'تذكير اجتماع'), ('grade_released', 'إعلان درجة'), ('certificate_issued', 'إصدار شهادة'), ('course_update', 'تحديث دورة'), ('system_announcement', 'إعلان نظام'), ('message', 'رسالة'), ('general', 'عام')], default='general', max_length=20, verbose_name='نوع الإشعار')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('normal', 'عادي'), ('high', 'عالي'), ('urgent', 'عاجل')], default='normal', max_length=10, verbose_name='الأولوية')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت القراءة')),
                ('email_sent', models.BooleanField(default=False, verbose_name='تم إرسال بريد إلكتروني')),
                ('push_sent', models.BooleanField(default=False, verbose_name='تم إرسال إشعار فوري')),
                ('action_url', models.URLField(blank=True, null=True, verbose_name='رابط الإجراء')),
                ('action_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='نص الإجراء')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='مجدول في')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='ينتهي في')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستلم')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method', models.CharField(choices=[('app', 'التطبيق'), ('email', 'البريد الإلكتروني'), ('push', 'إشعار فوري'), ('sms', 'رسالة نصية')], max_length=10, verbose_name='طريقة التوصيل')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('sent', 'تم الإرسال'), ('delivered', 'تم التوصيل'), ('failed', 'فشل'), ('bounced', 'مرتد')], default='pending', max_length=10, verbose_name='الحالة')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='رسالة الخطأ')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإرسال')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التوصيل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notification')),
            ],
            options={
                'verbose_name': 'سجل إشعار',
                'verbose_name_plural': 'سجلات الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_course_updates', models.BooleanField(default=True, verbose_name='تحديثات الدورات عبر البريد')),
                ('email_assignments', models.BooleanField(default=True, verbose_name='الواجبات عبر البريد')),
                ('email_exams', models.BooleanField(default=True, verbose_name='الامتحانات عبر البريد')),
                ('email_meetings', models.BooleanField(default=True, verbose_name='الاجتماعات عبر البريد')),
                ('email_grades', models.BooleanField(default=True, verbose_name='الدرجات عبر البريد')),
                ('email_certificates', models.BooleanField(default=True, verbose_name='الشهادات عبر البريد')),
                ('email_system', models.BooleanField(default=True, verbose_name='إعلانات النظام عبر البريد')),
                ('push_course_updates', models.BooleanField(default=True, verbose_name='تحديثات الدورات فورية')),
                ('push_assignments', models.BooleanField(default=True, verbose_name='الواجبات فورية')),
                ('push_exams', models.BooleanField(default=True, verbose_name='الامتحانات فورية')),
                ('push_meetings', models.BooleanField(default=True, verbose_name='الاجتماعات فورية')),
                ('push_grades', models.BooleanField(default=True, verbose_name='الدرجات فورية')),
                ('push_certificates', models.BooleanField(default=True, verbose_name='الشهادات فورية')),
                ('push_system', models.BooleanField(default=True, verbose_name='إعلانات النظام فورية')),
                ('digest_frequency', models.CharField(choices=[('never', 'أبداً'), ('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري')], default='weekly', max_length=10, verbose_name='تكرار الملخص')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='بداية الساعات الهادئة')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='نهاية الساعات الهادئة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'إعدادات الإشعارات',
                'verbose_name_plural': 'إعدادات الإشعارات',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم القالب')),
                ('notification_type', models.CharField(choices=[('course_enrollment', 'تسجيل في دورة'), ('assignment_due', 'موعد تسليم واجب'), ('exam_reminder', 'تذكير امتحان'), ('meeting_reminder', 'تذكير اجتماع'), ('grade_released', 'إعلان درجة'), ('certificate_issued', 'إصدار شهادة'), ('course_update', 'تحديث دورة'), ('system_announcement', 'إعلان نظام'), ('message', 'رسالة'), ('general', 'عام')], max_length=20, verbose_name='نوع الإشعار')),
                ('title_template', models.CharField(max_length=255, verbose_name='قالب العنوان')),
                ('message_template', models.TextField(verbose_name='قالب الرسالة')),
                ('email_subject_template', models.CharField(blank=True, max_length=255, null=True, verbose_name='قالب موضوع البريد')),
                ('email_body_template', models.TextField(blank=True, null=True, verbose_name='قالب نص البريد')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'قالب إشعار',
                'verbose_name_plural': 'قوالب الإشعارات',
                'unique_together': {('name', 'notification_type')},
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'),
        ),
    ]
