# Generated by Django 4.2.15 on 2025-07-31 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_code', models.CharField(choices=[('view_instructors', 'عرض المعلمين'), ('add_instructors', 'إضافة معلمين'), ('edit_instructors', 'تعديل المعلمين'), ('delete_instructors', 'حذف المعلمين'), ('view_students', 'عرض الطلاب'), ('add_students', 'إضافة طلاب'), ('edit_students', 'تعديل الطلاب'), ('delete_students', 'حذف الطلاب'), ('view_all_courses', 'عرض جميع الكورسات'), ('add_all_courses', 'إضافة جميع الكورسات'), ('edit_all_courses', 'تعديل جميع الكورسات'), ('delete_all_courses', 'حذف جميع الكورسات'), ('view_my_courses', 'عرض كورساتي'), ('add_my_courses', 'إضافة كورساتي'), ('edit_my_courses', 'تعديل كورساتي'), ('delete_my_courses', 'حذف كورساتي'), ('view_lessons', 'عرض الدروس'), ('add_lessons', 'إضافة دروس'), ('edit_lessons', 'تعديل الدروس'), ('delete_lessons', 'حذف الدروس'), ('view_modules', 'عرض الوحدات'), ('add_modules', 'إضافة وحدات'), ('edit_modules', 'تعديل الوحدات'), ('delete_modules', 'حذف الوحدات'), ('view_quizzes', 'عرض الاختبارات'), ('add_quizzes', 'إضافة اختبارات'), ('edit_quizzes', 'تعديل الاختبارات'), ('delete_quizzes', 'حذف الاختبارات'), ('view_questions', 'عرض الأسئلة'), ('add_questions', 'إضافة أسئلة'), ('edit_questions', 'تعديل الأسئلة'), ('delete_questions', 'حذف الأسئلة'), ('view_orders', 'عرض الطلبات'), ('add_orders', 'إضافة طلبات'), ('edit_orders', 'تعديل الطلبات'), ('delete_orders', 'حذف الطلبات'), ('view_payments', 'عرض المدفوعات'), ('add_payments', 'إضافة مدفوعات'), ('edit_payments', 'تعديل المدفوعات'), ('delete_payments', 'حذف المدفوعات'), ('view_coupons', 'عرض الكوبونات'), ('add_coupons', 'إضافة كوبونات'), ('edit_coupons', 'تعديل الكوبونات'), ('delete_coupons', 'حذف الكوبونات'), ('view_certificates', 'عرض الشهادات'), ('add_certificates', 'إضافة شهادات'), ('edit_certificates', 'تعديل الشهادات'), ('delete_certificates', 'حذف الشهادات'), ('view_reviews', 'عرض التقييمات'), ('add_reviews', 'إضافة تقييمات'), ('edit_reviews', 'تعديل التقييمات'), ('delete_reviews', 'حذف التقييمات'), ('view_banners', 'عرض اللافتات'), ('add_banners', 'إضافة لافتات'), ('edit_banners', 'تعديل اللافتات'), ('delete_banners', 'حذف اللافتات'), ('view_settings', 'عرض الإعدادات'), ('add_settings', 'إضافة إعدادات'), ('edit_settings', 'تعديل الإعدادات'), ('delete_settings', 'حذف الإعدادات'), ('view_meetings', 'عرض المحاضرات'), ('add_meetings', 'إضافة محاضرات'), ('edit_meetings', 'تعديل المحاضرات'), ('delete_meetings', 'حذف المحاضرات'), ('view_articles', 'عرض المقالات'), ('add_articles', 'إضافة مقالات'), ('edit_articles', 'تعديل المقالات'), ('delete_articles', 'حذف المقالات'), ('view_article_categories', 'عرض تصنيفات المقالات'), ('add_article_categories', 'إضافة تصنيفات مقالات'), ('edit_article_categories', 'تعديل تصنيفات المقالات'), ('delete_article_categories', 'حذف تصنيفات المقالات'), ('view_article_comments', 'عرض تعليقات المقالات'), ('add_article_comments', 'إضافة تعليقات مقالات'), ('edit_article_comments', 'تعديل تعليقات المقالات'), ('delete_article_comments', 'حذف تعليقات المقالات')], max_length=100, verbose_name='رمز الصلاحية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'صلاحية مخصصة',
                'verbose_name_plural': 'الصلاحيات المخصصة',
                'ordering': ['user', 'permission_code'],
                'unique_together': {('user', 'permission_code')},
            },
        ),
    ]
