# Generated by Django 5.2.1 on 2025-06-20 11:53

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الاجتماع')),
                ('description', models.TextField(verbose_name='وصف الاجتماع')),
                ('meeting_type', models.CharField(choices=[('ZOOM', 'اجتماع عبر زووم'), ('NORMAL', 'اجتماع عادي'), ('LIVE', 'اجتماع مباشر')], max_length=10, verbose_name='نوع الاجتماع')),
                ('start_time', models.DateTimeField(verbose_name='وقت البدء')),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=3600), verbose_name='المدة')),
                ('zoom_link', models.URLField(blank=True, null=True, verbose_name='رابط زووم')),
                ('recording_url', models.URLField(blank=True, null=True, verbose_name='رابط التسجيل')),
                ('materials', models.FileField(blank=True, null=True, upload_to='meeting_materials/', verbose_name='مواد الاجتماع')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('meeting_room_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='معرف غرفة الاجتماع')),
                ('is_live_started', models.BooleanField(default=False, verbose_name='بدأ الاجتماع المباشر')),
                ('live_started_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت بدء الاجتماع المباشر')),
                ('live_ended_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت انتهاء الاجتماع المباشر')),
                ('max_participants', models.IntegerField(default=50, verbose_name='الحد الأقصى للمشاركين')),
                ('enable_screen_share', models.BooleanField(default=True, verbose_name='تمكين مشاركة الشاشة')),
                ('enable_chat', models.BooleanField(default=True, verbose_name='تمكين الدردشة')),
                ('enable_recording', models.BooleanField(default=False, verbose_name='تمكين التسجيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('notification_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_meetings', to=settings.AUTH_USER_MODEL, verbose_name='منشئ الاجتماع')),
            ],
            options={
                'verbose_name': 'اجتماع',
                'verbose_name_plural': 'الاجتماعات',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='MeetingChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإرسال')),
                ('is_system_message', models.BooleanField(default=False, verbose_name='رسالة نظام')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='meetings.meeting', verbose_name='الاجتماع')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'رسالة دردشة',
                'verbose_name_plural': 'رسائل الدردشة',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('DAY_BEFORE', 'قبل يوم'), ('HOUR_BEFORE', 'قبل ساعة'), ('CANCELLED', 'تم الإلغاء'), ('RESCHEDULED', 'تم إعادة الجدولة'), ('CUSTOM', 'مخصص')], default='CUSTOM', max_length=20, verbose_name='نوع الإشعار')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('scheduled_time', models.DateTimeField(verbose_name='وقت الجدولة')),
                ('sent', models.BooleanField(default=False, verbose_name='تم الإرسال')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإرسال')),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='meetings.meeting', verbose_name='الاجتماع')),
                ('recipients', models.ManyToManyField(related_name='meeting_notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستلمون')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_attending', models.BooleanField(default=False, verbose_name='حاضر')),
                ('attendance_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت الحضور')),
                ('exit_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت المغادرة')),
                ('attendance_duration', models.DurationField(blank=True, null=True, verbose_name='مدة الحضور')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='meetings.meeting', verbose_name='الاجتماع')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مشارك',
                'verbose_name_plural': 'المشاركون',
                'unique_together': {('meeting', 'user')},
            },
        ),
    ]
