# Generated by Django 4.2.15 on 2025-08-17 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='رسالة الدعوة')),
                ('response', models.CharField(choices=[('pending', 'في الانتظار'), ('accepted', 'مقبول'), ('declined', 'مرفوض')], default='pending', max_length=20, verbose_name='الرد')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الرد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='meetings.meeting', verbose_name='الاجتماع')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'دعوة اجتماع',
                'verbose_name_plural': 'دعوات الاجتماعات',
                'ordering': ['-created_at'],
                'unique_together': {('meeting', 'user')},
            },
        ),
    ]
