# Generated by Django 4.2.15 on 2025-08-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meetinginvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='joined_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الانضمام'),
        ),
        migrations.AddField(
            model_name='participant',
            name='left_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت المغادرة'),
        ),
    ]
