# Generated by Django 4.2.15 on 2025-08-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_participant_joined_at_participant_left_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='attendance_status',
            field=models.CharField(choices=[('registered', 'مسجل'), ('present', 'حاضر'), ('absent', 'غائب'), ('late', 'متأخر'), ('not_marked', 'غير محدد')], default='registered', max_length=20, verbose_name='حالة الحضور'),
        ),
    ]
