# Generated by Django 4.2.15 on 2025-08-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'Video'), ('article', 'Article')], default='article', help_text='Type of the lesson', max_length=20, verbose_name='lesson type'),
        ),
    ]
