# Generated by Django 4.2.15 on 2025-09-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_lesson_lesson_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonresource',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata about the resource', null=True, verbose_name='metadata'),
        ),
        migrations.AlterField(
            model_name='moduleprogress',
            name='completion_requirements',
            field=models.JSONField(blank=True, default=dict, help_text='Structured data about completion requirements', null=True, verbose_name='completion requirements'),
        ),
        migrations.AlterField(
            model_name='moduleprogress',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata about the module progress', null=True, verbose_name='metadata'),
        ),
    ]
