# Generated by Django 4.2.15 on 2025-09-18 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_lessonresource_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='submodule',
            field=models.ForeignKey(blank=True, help_text='Parent module if this is a submodule (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submodules', to='content.module', verbose_name='submodule'),
        ),
    ]
