# Generated by Django 4.2.15 on 2025-09-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_add_submodule_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='bunny_video_id',
            field=models.CharField(blank=True, help_text='Bunny CDN video ID for external video hosting', max_length=100, null=True, verbose_name='Bunny video ID'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='bunny_video_url',
            field=models.URLField(blank=True, help_text='Direct URL to the video on Bunny CDN', null=True, verbose_name='Bunny video URL'),
        ),
        migrations.AddField(
            model_name='module',
            name='bunny_video_id',
            field=models.CharField(blank=True, help_text='Bunny CDN video ID for external video hosting', max_length=100, null=True, verbose_name='Bunny video ID'),
        ),
        migrations.AddField(
            model_name='module',
            name='bunny_video_url',
            field=models.URLField(blank=True, help_text='Direct URL to the video on Bunny CDN', null=True, verbose_name='Bunny video URL'),
        ),
    ]
