# Generated by Django 4.2.15 on 2025-09-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_lesson_bunny_video_id_lesson_bunny_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(blank=True, help_text='A short label containing only letters, numbers, underscores or hyphens for URLs', max_length=250, verbose_name='slug'),
        ),
    ]
