# Generated by Django 4.2.15 on 2025-08-22 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_add_default_categories'),
        ('store', '0002_paymentmethod_refundrequest_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='courses.enrollment'),
        ),
    ]
