# Generated by Django 4.2.15 on 2025-09-10 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_lessonresource_metadata_and_more'),
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='The lesson this question belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.lesson', verbose_name='Lesson'),
        ),
    ]
