# Generated by Django 4.2.15 on 2025-09-14 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_lessonresource_metadata_and_more'),
        ('assessment', '0002_questionbank_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='The lesson this flashcard belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='content.lesson', verbose_name='Lesson'),
        ),
    ]
