# Generated by Django 4.2.15 on 2025-09-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_flashcard_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='JSON array of tags for categorization', verbose_name='Tags'),
        ),
    ]
