# Generated by Django 5.2.1 on 2025-06-27 19:36

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم التصنيف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'تصنيف الكتب',
                'verbose_name_plural': 'تصنيفات الكتب',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='الرابط')),
                ('content', ckeditor.fields.RichTextField(verbose_name='المحتوى')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='ملخص')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النشر')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='الصورة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور'), ('archived', 'مؤرشف')], default='draft', max_length=20, verbose_name='الحالة')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True, verbose_name='وصف SEO')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='كلمات مفتاحية SEO')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='السماح بالتعليقات')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='الكاتب')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='courses.category', verbose_name='التصنيف')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='courses.tag', verbose_name='الوسوم')),
            ],
            options={
                'verbose_name': 'مقالة',
                'verbose_name_plural': 'المقالات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='محتوى التعليق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_approved', models.BooleanField(default=True, verbose_name='موافق عليه')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.article', verbose_name='المقالة')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='articles.articlecomment', verbose_name='التعليق الأصلي')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تعليق المقالة',
                'verbose_name_plural': 'تعليقات المقالات',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('author_name', models.CharField(max_length=255, verbose_name='اسم المؤلف')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('book_file', models.FileField(upload_to='books/', verbose_name='ملف الكتاب')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/covers/', verbose_name='صورة الغلاف')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاح')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='عدد التحميلات')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='حجم الملف (بايت)')),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, verbose_name='ISBN')),
                ('language', models.CharField(default='العربية', max_length=50, verbose_name='اللغة')),
                ('pages_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الصفحات')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='رفع بواسطة')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='articles.bookcategory', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'كتاب',
                'verbose_name_plural': 'الكتب',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['title'], name='articles_ar_title_ee81af_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', '-created_at'], name='articles_ar_status_1c9ff2_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['featured', '-created_at'], name='articles_ar_feature_080c05_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['author', '-created_at'], name='articles_ar_author__0bbe43_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='articles_bo_title_409d53_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['author_name'], name='articles_bo_author__ede27a_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['category'], name='articles_bo_categor_2b0cc3_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['is_available'], name='articles_bo_is_avai_8af0a9_idx'),
        ),
    ]
