# Generated by Django 4.1.7 on 2025-07-25 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articleview_articlerating_bookmark_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
    ]
