# Generated by Django 4.2.15 on 2025-08-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_complete_course',
            field=models.BooleanField(default=True, help_text='Check if this is a complete course with full content. Uncheck if this is just a course announcement/preview.', verbose_name='Is Complete Course'),
        ),
    ]
