# Generated by Django 4.2.15 on 2025-08-14 23:06

from django.db import migrations, models


def create_default_categories(apps, schema_editor):
    """Create default categories"""
    Category = apps.get_model('courses', 'Category')
    
    default_categories = [
        {
            'name': 'الدورات',
            'slug': 'courses',
            'description': 'دورات تعليمية متنوعة في مختلف المجالات',
            'order': 1,
            'is_default': True
        },
        {
            'name': 'التدريب الإلكتروني',
            'slug': 'e-learning',
            'description': 'برامج تدريبية إلكترونية تفاعلية',
            'order': 2,
            'is_default': True
        },
        {
            'name': 'الدبلومات',
            'slug': 'diplomas',
            'description': 'برامج دبلومة متخصصة وشهادات مهنية',
            'order': 3,
            'is_default': True
        }
    ]
    
    for category_data in default_categories:
        Category.objects.get_or_create(
            slug=category_data['slug'],
            defaults=category_data
        )


def reverse_default_categories(apps, schema_editor):
    """Remove default categories"""
    Category = apps.get_model('courses', 'Category')
    Category.objects.filter(is_default=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_is_complete_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Default categories cannot be deleted', verbose_name='Is Default Category'),
        ),
        migrations.RunPython(create_default_categories, reverse_default_categories),
    ]
