# Generated by Django 4.2.15 on 2025-09-18 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_subcategory_course_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
