# Generated by Django 4.2.15 on 2025-09-19 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_bunny_promotional_video_id_course_bunny_promotional_video_url'),
    ]

    operations = [
    ]
