# Generated by Django 4.1.7 on 2025-09-20 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_subcategory'),
        ('courses', '0008_merge_20250919_1814'),
    ]

    operations = [
    ]
