# Generated by Django 4.1.7 on 2025-07-25 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='نص الإجابة', max_length=1000)),
                ('is_correct', models.BooleanField(default=False, help_text='هل هذه الإجابة صحيحة؟')),
                ('explanation', models.TextField(blank=True, help_text='شرح الإجابة', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='ترتيب الإجابة')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='نص السؤال')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'اختيار من متعدد'), ('true_false', 'صح أو خطأ'), ('short_answer', 'إجابة قصيرة'), ('essay', 'مقال'), ('file_upload', 'رفع ملف')], default='essay', max_length=20)),
                ('points', models.PositiveIntegerField(default=1, help_text='الدرجة المخصصة لهذا السؤال')),
                ('explanation', models.TextField(blank=True, help_text='شرح السؤال أو الإجابة النموذجية', null=True)),
                ('image', models.ImageField(blank=True, help_text='صورة توضيحية للسؤال', null=True, upload_to='assignment_question_images/')),
                ('order', models.PositiveIntegerField(default=0, help_text='ترتيب السؤال')),
                ('is_required', models.BooleanField(default=True, help_text='هل السؤال إجباري؟')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_file',
            field=models.FileField(blank=True, help_text='ملف الواجب المرفق', null=True, upload_to='assignment_files/'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='has_file_upload',
            field=models.BooleanField(default=False, help_text='هل يسمح برفع ملفات؟'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='has_questions',
            field=models.BooleanField(default=False, help_text='هل يحتوي الواجب على أسئلة؟'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='submitted_file',
            field=models.FileField(blank=True, help_text='الملف المرفوع', null=True, upload_to='assignment_submissions/'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='submission_text',
            field=models.TextField(blank=True, help_text='النص المكتوب للإجابة'),
        ),
        migrations.CreateModel(
            name='AssignmentQuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, help_text='الإجابة النصية', null=True)),
                ('file_answer', models.FileField(blank=True, help_text='الملف المرفوع كإجابة', null=True, upload_to='assignment_question_files/')),
                ('points_earned', models.FloatField(default=0, help_text='الدرجة المكتسبة')),
                ('feedback', models.TextField(blank=True, help_text='ملاحظات المدرس على الإجابة')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.assignmentquestion')),
                ('selected_answer', models.ForeignKey(blank=True, help_text='الإجابة المختارة', null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.assignmentanswer')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='assignments.assignmentsubmission')),
            ],
        ),
        migrations.AddField(
            model_name='assignmentquestion',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assignments.assignment'),
        ),
        migrations.AddField(
            model_name='assignmentanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assignments.assignmentquestion'),
        ),
    ]
