# Generated by Django 4.2.15 on 2025-09-08 09:10

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignmentanswer_assignmentquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
