# Generated by Django 5.2.1 on 2025-06-27 19:36

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان البانر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('image', models.ImageField(upload_to='banners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='صورة البانر')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='رابط البانر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('banner_type', models.CharField(choices=[('main', 'Main Banner'), ('sidebar', 'Sidebar Banner'), ('promo', 'Promotional Banner')], default='main', max_length=20, verbose_name='نوع البانر')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ البدء')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'بانر',
                'verbose_name_plural': 'البانرات',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المجموعة')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='رابط المجموعة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(blank=True, related_name='collections', to='courses.course', verbose_name='الكورسات')),
            ],
            options={
                'verbose_name': 'مجموعة كورسات',
                'verbose_name_plural': 'مجموعات الكورسات',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
