# Generated by Django 4.2.15 on 2025-09-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='background_color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='لون الخلفية'),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نص الزر'),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='رابط الزر'),
        ),
        migrations.AddField(
            model_name='banner',
            name='text_color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='لون النص'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('main', 'Main Banner'), ('header', 'Header Banner'), ('sidebar', 'Sidebar Banner'), ('promo', 'Promotional Banner'), ('about_us', 'About Us Banner'), ('why_choose_us', 'Why Choose Us Banner')], default='main', max_length=20, verbose_name='نوع البانر'),
        ),
    ]
