# Generated by Django 5.2.1 on 2025-06-28 13:11

from django.db import migrations


def rename_tables(apps, schema_editor):
    # Rename tables
    schema_editor.execute('ALTER TABLE users_teacher RENAME TO users_instructor')
    schema_editor.execute('ALTER TABLE users_teacherapplication RENAME TO users_instructorapplication')
    
    # Update any foreign key references
    # Note: SQLite doesn't support direct foreign key constraint modifications,
    # so we'll need to handle this in the reverse migration if needed


def reverse_rename_tables(apps, schema_editor):
    # Reverse the renaming
    schema_editor.execute('ALTER TABLE users_instructor RENAME TO users_teacher')
    schema_editor.execute('ALTER TABLE users_instructorapplication RENAME TO users_teacherapplication')


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_alter_instructor_options'),
    ]

    operations = [
        migrations.RunPython(rename_tables, reverse_code=reverse_rename_tables),
    ]
