# Generated by Django 5.2.1 on 2025-06-29 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_teacher_to_instructor_tables'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstructorApplication',
        ),
    ]
