# Generated by Django 4.1.7 on 2025-07-10 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_created_at'),
        ('users', '0004_delete_instructorapplication'),
    ]

    operations = [
    ]
