# Generated by Django 5.2.1 on 2025-06-27 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresetCertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم القالب الجاهز')),
                ('description', models.TextField(verbose_name='وصف القالب')),
                ('template_style', models.CharField(choices=[('modern', 'تصميم حديث'), ('classic', 'تصميم كلاسيكي'), ('elegant', 'تصميم أنيق'), ('professional', 'تصميم مهني'), ('creative', 'تصميم إبداعي'), ('minimalist', 'تصميم بسيط'), ('colorful', 'تصميم ملون'), ('corporate', 'تصميم شركات')], max_length=20, verbose_name='نمط القالب')),
                ('primary_color', models.CharField(default='#2a5a7c', max_length=7, verbose_name='اللون الأساسي')),
                ('secondary_color', models.CharField(default='#28a745', max_length=7, verbose_name='اللون الثانوي')),
                ('background_pattern', models.CharField(default='none', max_length=50, verbose_name='نمط الخلفية')),
                ('border_style', models.CharField(default='classic', max_length=50, verbose_name='نمط الحدود')),
                ('font_family', models.CharField(default='Arial', max_length=100, verbose_name='نوع الخط')),
                ('preview_image', models.ImageField(upload_to='preset_templates/', verbose_name='صورة المعاينة')),
                ('template_html', models.TextField(verbose_name='كود HTML للقالب')),
                ('template_css', models.TextField(verbose_name='كود CSS للقالب')),
                ('category', models.CharField(default='general', max_length=50, verbose_name='التصنيف')),
                ('is_featured', models.BooleanField(default=False, verbose_name='قالب مميز')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'قالب جاهز',
                'verbose_name_plural': 'القوالب الجاهزة',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=255, verbose_name='اسم القالب')),
                ('template_style', models.CharField(choices=[('modern', 'تصميم حديث'), ('classic', 'تصميم كلاسيكي'), ('elegant', 'تصميم أنيق'), ('professional', 'تصميم مهني'), ('creative', 'تصميم إبداعي'), ('minimalist', 'تصميم بسيط'), ('colorful', 'تصميم ملون'), ('corporate', 'تصميم شركات')], default='modern', max_length=20, verbose_name='نمط الشهادة')),
                ('template_source', models.CharField(choices=[('custom', 'قالب مخصص'), ('preset', 'قالب جاهز'), ('imported', 'قالب مستورد')], default='custom', max_length=20, verbose_name='مصدر القالب')),
                ('primary_color', models.CharField(choices=[('#2a5a7c', 'أزرق'), ('#28a745', 'أخضر'), ('#dc3545', 'أحمر'), ('#ffc107', 'أصفر'), ('#6f42c1', 'بنفسجي'), ('#fd7e14', 'برتقالي'), ('#17a2b8', 'سماوي'), ('#e83e8c', 'وردي'), ('#6c757d', 'رمادي'), ('#343a40', 'أسود')], default='#2a5a7c', max_length=7, verbose_name='اللون الأساسي')),
                ('secondary_color', models.CharField(choices=[('#2a5a7c', 'أزرق'), ('#28a745', 'أخضر'), ('#dc3545', 'أحمر'), ('#ffc107', 'أصفر'), ('#6f42c1', 'بنفسجي'), ('#fd7e14', 'برتقالي'), ('#17a2b8', 'سماوي'), ('#e83e8c', 'وردي'), ('#6c757d', 'رمادي'), ('#343a40', 'أسود')], default='#28a745', max_length=7, verbose_name='اللون الثانوي')),
                ('institution_name', models.CharField(max_length=255, verbose_name='اسم المؤسسة')),
                ('institution_logo', models.ImageField(blank=True, null=True, upload_to='certificate_templates/logos/', verbose_name='شعار المؤسسة')),
                ('signature_name', models.CharField(max_length=255, verbose_name='اسم الموقع')),
                ('signature_title', models.CharField(max_length=255, verbose_name='منصب الموقع')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='certificate_templates/signatures/', verbose_name='صورة التوقيع')),
                ('user_signature', models.ImageField(blank=True, null=True, upload_to='certificate_templates/user_signatures/', verbose_name='توقيع المستخدم')),
                ('certificate_text', models.TextField(default='هذا يشهد بأن {student_name} قد أكمل بنجاح دورة {course_name} بتاريخ {completion_date}', help_text='يمكنك استخدام المتغيرات: {student_name}, {course_name}, {completion_date}, {institution_name}', verbose_name='نص الشهادة')),
                ('background_pattern', models.CharField(default='none', max_length=50, verbose_name='نمط الخلفية')),
                ('border_style', models.CharField(default='classic', max_length=50, verbose_name='نمط الحدود')),
                ('font_family', models.CharField(default='Arial', max_length=100, verbose_name='نوع الخط')),
                ('include_qr_code', models.BooleanField(default=True, verbose_name='إضافة رمز QR للتحقق')),
                ('include_grade', models.BooleanField(default=False, verbose_name='إضافة الدرجة في الشهادة')),
                ('include_completion_date', models.BooleanField(default=True, verbose_name='إضافة تاريخ الإكمال')),
                ('include_course_duration', models.BooleanField(default=False, verbose_name='إضافة مدة الدورة')),
                ('preview_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات المعاينة')),
                ('is_public', models.BooleanField(default=False, verbose_name='قالب عام (يمكن للجميع استخدامه)')),
                ('is_default', models.BooleanField(default=False, verbose_name='القالب الافتراضي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='منشئ القالب')),
            ],
            options={
                'verbose_name': 'قالب الشهادة',
                'verbose_name_plural': 'قوالب الشهادات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_name', models.CharField(max_length=255, verbose_name='اسم التوقيع')),
                ('signature_image', models.ImageField(upload_to='user_signatures/', verbose_name='صورة التوقيع')),
                ('signature_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='المنصب')),
                ('is_default', models.BooleanField(default=False, verbose_name='التوقيع الافتراضي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'توقيع المستخدم',
                'verbose_name_plural': 'توقيعات المستخدمين',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(max_length=100, unique=True, verbose_name='رقم الشهادة')),
                ('date_issued', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإصدار')),
                ('completion_date', models.DateTimeField(verbose_name='تاريخ إكمال الدورة')),
                ('student_name', models.CharField(max_length=255, verbose_name='اسم الطالب')),
                ('course_title', models.CharField(max_length=500, verbose_name='عنوان الدورة')),
                ('institution_name', models.CharField(default='أكاديمية التعلم الإلكتروني', max_length=255, verbose_name='اسم المؤسسة')),
                ('final_grade', models.FloatField(blank=True, null=True, verbose_name='الدرجة النهائية')),
                ('completion_percentage', models.FloatField(default=100.0, verbose_name='نسبة الإكمال')),
                ('course_duration_hours', models.IntegerField(blank=True, null=True, verbose_name='مدة الدورة بالساعات')),
                ('status', models.CharField(choices=[('active', 'نشطة'), ('revoked', 'ملغية'), ('expired', 'منتهية الصلاحية')], default='active', max_length=20, verbose_name='حالة الشهادة')),
                ('verification_status', models.CharField(choices=[('verified', 'تم التحقق'), ('pending', 'في انتظار التحقق'), ('failed', 'فشل التحقق')], default='verified', max_length=20, verbose_name='حالة التحقق')),
                ('verification_code', models.CharField(max_length=50, unique=True, verbose_name='رمز التحقق')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/pdfs/', verbose_name='ملف PDF')),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='certificates/qr_codes/', verbose_name='صورة رمز QR')),
                ('digital_signature', models.TextField(blank=True, null=True, verbose_name='التوقيع الرقمي')),
                ('signature_verified', models.BooleanField(default=False, verbose_name='تم التحقق من التوقيع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course', verbose_name='الدورة')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL, verbose_name='أصدرت بواسطة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificates.certificatetemplate', verbose_name='قالب الشهادة')),
            ],
            options={
                'verbose_name': 'شهادة',
                'verbose_name_plural': 'الشهادات',
                'ordering': ['-date_issued'],
                'indexes': [models.Index(fields=['certificate_id'], name='certificate_certifi_5672de_idx'), models.Index(fields=['verification_code'], name='certificate_verific_e033f7_idx'), models.Index(fields=['user', 'course'], name='certificate_user_id_2a7ce8_idx'), models.Index(fields=['status'], name='certificate_status_31e804_idx'), models.Index(fields=['verification_status'], name='certificate_verific_4949c7_idx')],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
