# Generated by Django 4.2.15 on 2025-09-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PresetCertificateTemplate',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='background_pattern',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='border_style',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='font_family',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='preview_data',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='secondary_color',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='template_source',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='template_style',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='user_signature',
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='template_file',
            field=models.FileField(blank=True, help_text='يمكن رفع ملف HTML أو صورة للقالب', null=True, upload_to='certificate_templates/files/', verbose_name='ملف القالب الجاهز'),
        ),
    ]
